version: '3.8'

services:
  ros_container:
    build: .
    container_name: ros_yolo
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - LIBGL_ALWAYS_INDIRECT=0
      - QT_X11_NO_MITSHM=1
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # X11 forwarding for GUI tools
    network_mode: "host"
    tty: true  # Keep terminal open
    stdin_open: true  # Allow interactive commands

